### ISSUE TITLE
React Player 적용

### ISSUE THREAD

**Issue by sonwonjae** [Numble-challenge-Team/client#12]
### ISSUE

- Type: feat
- Page: my-video

### TODO

- [x] 팀원들과 React-Player 적용여부에 대해 토의하기
- [x] 모든 미리보기 React-Player로 변경하기
- [x] react strictmode와 충돌문제 해결을 위해 strictmode off

**Comment by sonwonjae** [comment]
react strict mode와 충돌 문제 관련 ISSUE

https://github.com/cookpete/react-player/issues/1439
