### ISSUE TITLE
비디오 상세 페이지 UI 작업

### ISSUE THREAD

**Issue by useonglee** [Numble-challenge-Team/client#25]
### ISSUE
- Type: feature
- Page: video detail

### TODO
- [x] 상세 비디오 화면 컴포넌트 UI
- [x] 비디오 상세 설명 컴포넌트 UI
- [x] 관련 영상 컴포넌트 UI
- [x] 댓글 컴포넌트 UI
