### ISSUE TITLE
마이 비디오 페이지 - 영상 업로드 구현

### ISSUE THREAD

**Issue by sonwonjae** [Numble-challenge-Team/client#7]
### ISSUE

- Type: feature
- Page: my-video/add

### TODO

- [x] drag & drop을 통한 파일 업로드
- [x] click을 통한 파일 업로드
- [x] 영상, 이미지 미리보기
- [x] 업로드 탭 `input` 스타일 적용
- [x] `form` 레이아웃 스타일 적용
- [x] 영상, 이미지 알맞지 않은 확장자 분기 처리하기
- [x] `required`를 모두 통과한 뒤 `submit`버튼 활성화 하기
- [x] 한번 업로드 이후 업로드한 파일 변경하는 기능 구현
- [x] `multipart/form-data` 세팅
- [x] 설명 입력 창에 `Enter` 처리
- [x] 늘어나는 `textarea` 설정 -> `contentediable` 사용
- [x] 용량 제한 유효성 체크하기
- [x] 유효성 체크에 대한 에러메시지 제공
- [x] 임베드, 직접 영상 업로드 분기 처리하기
- [x] 임베드 영상 유효성 체크하기
- [x] 해시태그 UI 추가
- [x] 상태관리 atom으로 전부 변경
- [x] 공통 폼 파트 컴포넌트 화
- [x] 영상 업로드 페이지에서 나가려고 할 때 UI 제공
- [x] 영상 업로드 제출 후 로딩 구현
- [x] 영상 업로드 실패 시 UI 구현
- [x] 영상 업로드 성공 시 UI 구현
- [x] 세로 이미지, 영상 관련 처리
- [x] 임베드 영상 없을 시 스켈레톤 UI 처리

**Comment by sonwonjae** [comment]
영상 업로드 유효성 체크 시 애초에 잘못된 확장자면 받아들이지 않는데 에러메시지가 필요할까?

**Comment by sonwonjae** [comment]
영상, 이미지 업로드 시 업로드할 파일이 없으면 제출 버튼이 활성화되지 않는데 유효성검사가 필요할까?

**Comment by sonwonjae** [comment]
> 영상, 이미지 업로드 시 업로드할 파일이 없으면 제출 버튼이 활성화되지 않는데 유효성검사가 필요할까?

클라이언트 측에서 `disabled`를 제거해버리면 제출버튼을 강제로 활성화시킬 수 있으니 이 부분은 필요할 수도 있을듯
