### ISSUE TITLE
공통 레이아웃 및 컬러시스템 설정

### ISSUE THREAD

**Issue by sonwonjae** [Numble-challenge-Team/client#9]
### ISSUE

- Type: style
- Page: -

### TODO

- [x] 컬러시스템 구축
- [x] 컬러시스템 타입 힌트 설정
- [x] 레이아웃 `main` 설정
- [x] 네비게이션 스타일링
- [x] `hasHeader`로 헤더 컴포넌트 사용여부 분기처리
- [x] 컴포넌트 화살표 함수에서 일반 함수로 수정
